### ISSUE TITLE
<cell rend="right">

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/PDF-Files#7]
See file liv_000001

`<cell rend="right">` renders rather too far too the right. See page 0104 for an example. The distance between the left and right cells could be cut in half.

**Comment by jamescummings** [comment]
@awisnicki: 
I think this is happening because the general width of the table. This then looks weird because the normal text has linebreaks creating quite short lines (as in the diary). 

One solution to this might be to force the default width of the table to be less wide.  This would affect all tables.  How do you feel about that as a possibility? I'd also want to left-align the table (since technically they are centred) as a whole.

**Comment by awisnicki** [comment]
Yes, making the table less wide sounds good. Give it a try of 50% of what it currently is, per my first comment of cutting in half. Left aligning sounds good.

**Comment by jamescummings** [comment]
Believe I've fixed this by doing the above.

**Comment by awisnicki** [comment]
Better, but still a bit far out. Bring it in to the left by another 50% please.

**Comment by jamescummings** [comment]
I've brought it in a bit more, if that is enough, close issue.

**Comment by awisnicki** [comment]
And that's a wrap. Thank you!
